#!/bin/sh
#
# /etc/rc.d/obexd: start/stop/restart obex daemon
#

case $1 in
start)
	/usr/libexec/obex/obexd &
	;;
stop)
	pkill obexd
	;;
restart)
	$0 stop && sleep 2 && $0 start
	;;
*)
	echo "usage: $0 [start|stop|restart]"
	;;
esac

# End of file
